alias: UC1 Ambient Temperature
description: Automatically controls the fan and window based on ambient temperature.
triggers:
  - alias: Interior above 25°C
    trigger: numeric_state
    entity_id:
      - sensor.esphome_web_99cff8_temperature
    above: 25
    id: interior_hot
  - alias: Interior below 22°C
    trigger: numeric_state
    entity_id:
      - sensor.esphome_web_99cff8_temperature
    id: interior_cold
    below: 22
  - trigger: numeric_state
    entity_id:
      - sensor.esphome_web_99cff8_temperature
    above: 22
    below: 25
    id: desired_temps
  - trigger: numeric_state
    entity_id:
      - input_number.aussen_temperatur
    id: outside_good
    above: 22
    below: 25
  - trigger: numeric_state
    entity_id:
      - input_number.aussen_temperatur
    above: 25
    id: outside_hot
  - type: temperature
    device_id: 95e14c9e384e633135ccddd4fb26acc9
    entity_id: a5853b33b8721b7db35d80196d758556
    domain: sensor
    trigger: device
    id: outside_cold
    below: 22
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - interior_hot
              - outside_good
          - condition: numeric_state
            entity_id: input_number.aussen_temperatur
            below: 25
        sequence:
          - action: fan.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: fan.esphome_web_99cff8_dc_fan
          - action: cover.open_cover
            metadata: {}
            data: {}
            target:
              entity_id: cover.esphome_web_99cff8_fenster
          - delay: "00:00:01"
          - action: cover.stop_cover
            metadata: {}
            data: {}
            target:
              entity_id: cover.esphome_web_99cff8_fenster
      - conditions:
          - condition: trigger
            id:
              - interior_cold
              - outside_good
          - condition: numeric_state
            entity_id: input_number.aussen_temperatur
            above: 22
        sequence:
          - action: cover.open_cover
            metadata: {}
            data: {}
            target:
              entity_id: cover.esphome_web_99cff8_fenster
          - action: fan.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: fan.esphome_web_99cff8_dc_fan
          - delay: "00:00:01"
          - action: cover.stop_cover
            metadata: {}
            data: {}
            target:
              entity_id: cover.esphome_web_99cff8_fenster
      - conditions:
          - condition: trigger
            id:
              - outside_cold
              - desired_temps
              - outside_hot
        sequence:
          - action: cover.close_cover
            metadata: {}
            data: {}
            target:
              entity_id: cover.esphome_web_99cff8_fenster
          - action: fan.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: fan.esphome_web_99cff8_dc_fan
          - delay: "00:00:01"
          - action: cover.stop_cover
            metadata: {}
            data: {}
            target:
              entity_id: cover.esphome_web_99cff8_fenster
mode: single
