alias: UC2 Moisture Control
description: Turns fan on/off based on moisture sensor
triggers:
  - type: moist
    device_id: 95e14c9e384e633135ccddd4fb26acc9
    entity_id: eb6d04ca2cfcf47f16a26a3d8af5fb69
    domain: binary_sensor
    trigger: device
    id: moist
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - moist
          - condition: numeric_state
            entity_id: sensor.esphome_web_99cff8_humidity
            above: 60
        sequence:
          - repeat:
              while:
                - condition: numeric_state
                  entity_id: sensor.esphome_web_99cff8_humidity
                  above: 60
              sequence:
                - if:
                    - condition: device
                      device_id: 95e14c9e384e633135ccddd4fb26acc9
                      domain: fan
                      entity_id: fan.esphome_web_99cff8_dc_fan
                      type: is_off
                  then:
                    - type: turn_on
                      device_id: 95e14c9e384e633135ccddd4fb26acc9
                      entity_id: fan.esphome_web_99cff8_dc_fan
                      domain: fan
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
          - type: turn_off
            device_id: 95e14c9e384e633135ccddd4fb26acc9
            entity_id: fan.esphome_web_99cff8_dc_fan
            domain: fan
mode: single
