alias: UC1 Ambient Temperature
description: Automatically controls the fan and window based on ambient temperature.
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.esphome_web_99cff8_temperature
    above: input_number.aussen_temperatur
    id: hot
  - trigger: numeric_state
    entity_id:
      - sensor.esphome_web_99cff8_temperature
    id: cold
    below: input_number.aussen_temperatur
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: hot
        sequence:
          - type: turn_on
            device_id: 95e14c9e384e633135ccddd4fb26acc9
            entity_id: fan.esphome_web_99cff8_dc_fan
            domain: fan
          - device_id: 95e14c9e384e633135ccddd4fb26acc9
            domain: cover
            entity_id: cover.esphome_web_99cff8_fenster
            type: open
          - delay: "00:00:01"
          - device_id: 95e14c9e384e633135ccddd4fb26acc9
            domain: cover
            entity_id: cover.esphome_web_99cff8_fenster
            type: stop
      - conditions:
          - condition: trigger
            id: cold
        sequence:
          - type: turn_off
            device_id: 95e14c9e384e633135ccddd4fb26acc9
            entity_id: fan.esphome_web_99cff8_dc_fan
            domain: fan
          - device_id: 95e14c9e384e633135ccddd4fb26acc9
            domain: cover
            entity_id: cover.esphome_web_99cff8_fenster
            type: close
          - delay: "00:00:01"
          - device_id: 95e14c9e384e633135ccddd4fb26acc9
            domain: cover
            entity_id: cover.esphome_web_99cff8_fenster
            type: stop
mode: single
