alias: UC3 Gas Detection
description: ""
triggers:
  - id: gas
    type: gas
    trigger: device
    device_id: 66c17f462dd54503a9410404ea12080e
    entity_id: 6a49e2c37bf6c8b0ec53e5fc9c3b4cae
    domain: binary_sensor
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - gas
        sequence:
          - parallel:
              - parallel:
                  - type: turn_on
                    device_id: 66c17f462dd54503a9410404ea12080e
                    entity_id: 14b90bba275ead15edcfa5501c3275fa
                    domain: switch
                  - delay:
                      hours: 0
                      minutes: 0
                      seconds: 5
                      milliseconds: 0
                  - type: turn_off
                    device_id: 66c17f462dd54503a9410404ea12080e
                    entity_id: 14b90bba275ead15edcfa5501c3275fa
                    domain: switch
              - device_id: 66c17f462dd54503a9410404ea12080e
                domain: light
                entity_id: 84da28278320372e310554e8819fbb57
                type: flash
              - parallel:
                  - device_id: 66c17f462dd54503a9410404ea12080e
                    domain: cover
                    entity_id: 979506d6128a44847aefc8ca1602d3c0
                    type: open
                  - delay:
                      hours: 0
                      minutes: 0
                      seconds: 1
                      milliseconds: 0
                  - device_id: 66c17f462dd54503a9410404ea12080e
                    domain: cover
                    entity_id: 979506d6128a44847aefc8ca1602d3c0
                    type: stop
          - wait_for_trigger:
              - type: no_gas
                device_id: 66c17f462dd54503a9410404ea12080e
                entity_id: 6a49e2c37bf6c8b0ec53e5fc9c3b4cae
                domain: binary_sensor
                trigger: device
          - type: turn_off
            device_id: 66c17f462dd54503a9410404ea12080e
            entity_id: 84da28278320372e310554e8819fbb57
            domain: light
          - device_id: 66c17f462dd54503a9410404ea12080e
            domain: cover
            entity_id: 979506d6128a44847aefc8ca1602d3c0
            type: close
          - delay:
              hours: 0
              minutes: 0
              seconds: 1
              milliseconds: 0
          - device_id: 66c17f462dd54503a9410404ea12080e
            domain: cover
            entity_id: 979506d6128a44847aefc8ca1602d3c0
            type: stop
mode: single
