alias: UC3 Gas Detection
description: ""
triggers:
  - id: gas
    type: gas
    trigger: device
    device_id: 95e14c9e384e633135ccddd4fb26acc9
    entity_id: binary_sensor.esphome_web_99cff8_gas_sensor
    domain: binary_sensor
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - gas
        sequence:
          - action: mqtt.publish
            metadata: {}
            data:
              topic: haus_rene/gas
              payload: "ON"
          - parallel:
              - sequence:
                  - type: turn_on
                    device_id: 95e14c9e384e633135ccddd4fb26acc9
                    entity_id: b22ab727e76fd185a8a23d7b9c20af73
                    domain: switch
                  - delay:
                      hours: 0
                      minutes: 0
                      seconds: 5
                      milliseconds: 0
                  - type: turn_off
                    device_id: 95e14c9e384e633135ccddd4fb26acc9
                    entity_id: b22ab727e76fd185a8a23d7b9c20af73
                    domain: switch
              - sequence:
                  - device_id: 95e14c9e384e633135ccddd4fb26acc9
                    domain: cover
                    entity_id: cover.esphome_web_99cff8_fenster
                    type: open
                  - delay:
                      hours: 0
                      minutes: 0
                      seconds: 1
                      milliseconds: 0
                  - device_id: 95e14c9e384e633135ccddd4fb26acc9
                    domain: cover
                    entity_id: cover.esphome_web_99cff8_fenster
                    type: stop
              - device_id: 95e14c9e384e633135ccddd4fb26acc9
                domain: light
                entity_id: light.esphome_web_99cff8_warning_indicator
                type: flash
              - sequence:
                  - wait_for_trigger:
                      - type: no_gas
                        device_id: 95e14c9e384e633135ccddd4fb26acc9
                        entity_id: binary_sensor.esphome_web_99cff8_gas_sensor
                        domain: binary_sensor
                        trigger: device
                  - delay:
                      hours: 0
                      minutes: 0
                      seconds: 10
                      milliseconds: 0
                  - action: mqtt.publish
                    metadata: {}
                    data:
                      topic: haus_rene/gas
                      payload: "OFF"
                  - type: turn_off
                    device_id: 95e14c9e384e633135ccddd4fb26acc9
                    entity_id: light.esphome_web_99cff8_warning_indicator
                    domain: light
                  - device_id: 95e14c9e384e633135ccddd4fb26acc9
                    domain: cover
                    entity_id: cover.esphome_web_99cff8_fenster
                    type: close
                  - delay:
                      hours: 0
                      minutes: 0
                      seconds: 1
                      milliseconds: 0
                  - device_id: 95e14c9e384e633135ccddd4fb26acc9
                    domain: cover
                    entity_id: cover.esphome_web_99cff8_fenster
                    type: stop
mode: single
